# Generated by Django 5.1.3 on 2024-11-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
