# Generated by Django 5.1.3 on 2024-11-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0002_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('desc', models.TextField(max_length=300)),
            ],
        ),
    ]
