# Generated by Django 5.1.3 on 2024-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
